# Nombre de la aplicacion
spring.application.name=BackendDineMeNow

#conexion a la base de datos MongoDB
spring.mongodb.uri=mongodb://localhost:27017/DineMeNow

# Configuracion del puerto del servidor
server.port=8080

# Log de Spring - Nivel INFO para ver solo lo importante
logging.level.org.springframework=INFO



#configuracion gmail
#Servidor SMTP de Gmail
spring.mail.host=smtp.gmail.com

#Es el puerto de conexión al servidor. El 587 es el estándar para envío de correos con seguridad STARTTLS. No cambiar
spring.mail.port=587

#Nombre de usuario para autenticarse en el servidor SMTP. En este caso, nuestra dirección de correo electrónico de Gmail.
spring.mail.username=a@gmail.com

#Contraseña de la cuenta de Gmail. Para mayor seguridad, se recomienda usar una contraseña de aplicación en lugar de la contraseña principal de la cuenta.
spring.mail.password= ${MATH}

# Activa el cifrado de la conexión. Básicamente protege los datos que viajan entre la app y el servidor de Gmail. Siempre va en true.
spring.mail.properties.mail.smtp.starttls.enable=true

#Le dice a Spring que el servidor requiere autenticación, es decir, que sí necesita usuario y contraseña para enviar correos. Siempre va en true.
spring.mail.properties.mail.smtp.auth=true

app.mail.from=DineMeNow <dinemenow2@gmail.com>

# Configuración para mostrar detalles de errores en las respuestas HTTP
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always

spring.data.mongodb.auto-index-creation=true