# Nombre de la aplicacion
spring.application.name=BackendDineMeNow

#conexion a la base de datos MongoDB
spring.mongodb.uri=mongodb://localhost:27017/DineMeNow

# Configuracion del puerto del servidor
server.port=8080

#Log de mongo, solo desarrollo(quitar)
logging.level.org.springframework=DEBUG